const {test} = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {Database} = require('../server/database.cjs');
const {createService} = require('../server/index.cjs');
const {Store} = require('../src/store.cjs');
const {TeamClient} = require('../src/team-client.cjs');
const csv = 'Email,Status,Full Name,VM Account,Proxy Details,Password\na@example.test,Active,Alice,GoLogin,192.0.2.1:8080:test:proxy-secret,excluded-password\nb@example.test,Active,Bob,Marketing,,excluded-password\nc@example.test,Inactive,Carol,GoLogin,,excluded-password';
const sheetUrl = 'https://docs.google.com/spreadsheets/d/test-sheet/edit#gid=1';
const key = 'ab'.repeat(32);
test('sheet profiles retain identity and sessions while proxies and folders change; inactive accounts archive', async t => {
 const root = fs.mkdtempSync(path.join(os.tmpdir(),'ortus-db-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
 const db = new Database(root,key);const sync = text => db.syncSheet(sheetUrl,async()=>({ok:true,text:async()=>text}));
 await sync(csv);assert.equal(db.list().length,2);const p=db.list()[0];assert.equal(p.proxy.password,'proxy-secret');
 assert(!JSON.stringify(db.data).includes('excluded-password'));
 assert(!fs.readFileSync(db.file).includes(Buffer.from('proxy-secret')));
 await sync(csv.replace('Alice,GoLogin,192.0.2.1:8080:test:proxy-secret','Alicia,New folder,192.0.2.2:9000:test:changed'));
 assert.equal(db.list()[0].name,'a@example.test');assert.equal(db.list()[0].id,p.id);assert.equal(db.list()[0].folder,'New folder');assert.equal(db.list()[0].proxy.password,'changed');
 assert.throws(()=>db.update(p.id,{...p,name:'stale'}),/Another Mac/);
 await sync(csv.replace('a@example.test,Active','a@example.test,Inactive'));assert.equal(db.list().length,1);assert(db.get(p.id).archived);
 assert.equal(new Database(root,key).list().length,1);
});
test('two clean Macs load shared proxies, exchange new profiles/settings, and retain local-only sessions', async t => {
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'ortus-team-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
 const token='t'.repeat(40);const {server,db}=createService({root:path.join(root,'server'),storageKey:key,token,adminToken:'a'.repeat(40)});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>server.close());
 await db.syncSheet(sheetUrl,async()=>({ok:true,text:async()=>csv}));
 const baseUrl=`http://127.0.0.1:${server.address().port}/profile-desk/v1`;
 const encryption={encryptString:s=>Buffer.from(s),decryptString:b=>b.toString()};
 const storeA=new Store(path.join(root,'a'),encryption),storeB=new Store(path.join(root,'b'),encryption);
 const a=new TeamClient(storeA,{baseUrl,token,testing:true}),b=new TeamClient(storeB,{baseUrl,token,testing:true});
 assert.equal((await fetch(baseUrl+'/profiles')).status,401);
 await a.refresh();await b.refresh();assert.equal(storeA.list().length,2);assert.equal(storeB.list().length,2);
 const id=storeA.list()[0].id;assert.equal(storeB.get(id).proxy.password,'proxy-secret');assert(!JSON.stringify(storeB.list()).includes('proxy-secret'));
 storeB.update(id,{cookies:[{name:'session',value:'local-cookie'}]});
 const created=await a.create({name:'Team account',folder:'New folder',proxy:{mode:'http',host:'192.0.2.3',port:8080,username:'u',password:'new-secret'}});
 await b.refresh();assert.equal(storeB.get(created.id).folder,'New folder');assert.equal(storeB.get(created.id).proxy.password,'new-secret');
 await a.update(created.id,{...created,name:'Renamed'},created.version);await b.refresh();assert.equal(storeB.get(created.id).name,'Renamed');
 await assert.rejects(b.update(created.id,{...created,name:'Stale'},created.version),/Another Mac/);
 assert.equal(storeB.get(id).cookies[0].value,'local-cookie');
 const denied=new TeamClient(storeB,{baseUrl,token:'x'.repeat(40),testing:true});await assert.rejects(denied.refresh(),/access expired/);assert.equal(storeB.list().length,3);
 assert.equal((await fetch(baseUrl+`/profiles/${id}/snapshot`,{headers:{Authorization:`Bearer ${token}`}})).status,405);
});
